In [1]:
import numpy as np 

In [2]:
listy = [1,2,3,4,5]
arr = np.array(listy)

print("Array: ",arr)
print("Shape: ",arr.shape)
print("DataType: ",arr.dtype)

Array:  [1 2 3 4 5]
Shape:  (5,)
DataType:  int64


In [4]:
zm = np.zeros((3,3))
om = np.ones((2,5))

print("\n3x3 Zero Matrix: \n",zm)
print("Shape: ",zm.shape)

print("\n3x3 Ones Matrix: \n",om)
print("Shape: ",om.shape)



3x3 Zero Matrix: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Shape:  (3, 3)

3x3 Ones Matrix: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Shape:  (2, 5)


In [5]:
arrtwelve = np.arange(1,13)
resarr = arrtwelve.reshape(3,4)

print("\nOriginal Array:", arrtwelve)
print("Shape:", arrtwelve.shape)


print("\nReshaped Array:\n", resarr)
print("Shape:", resarr.shape)


Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape: (12,)

Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)


In [9]:
randarr = np.random.randint(1,100,10)

print("\nRandom Array:", randarr)
print("Min:", randarr.min())
print("Max:", randarr.max())
print("Mean:", randarr.mean())
print("Sum:", randarr.sum())
print("Standard Deviation:", randarr.std())


Random Array: [43 42 99 88 98 31 30 46 65 48]
Min: 30
Max: 99
Mean: 59.0
Sum: 590
Standard Deviation: 25.412595302329905


In [11]:
import pandas as pd 

In [16]:
studdata = {
    "Name ": ["Varun","Yug","Vaibhav","Sushant"],
    "Marks": [100,98,85,74]
}
df_stud = pd.DataFrame(studdata)

print("\nStudent DataFrame:\n", df_stud)
print("\nData types:\n", df_stud.dtypes)


Student DataFrame:
      Name   Marks
0    Varun    100
1      Yug     98
2  Vaibhav     85
3  Sushant     74

Data types:
 Name     object
Marks     int64
dtype: object


In [19]:
df_csv = pd.read_csv("data.csv")


print("\nFirst 5 records:\n", df_csv.head())
print("\nLast 5 records:\n", df_csv.tail())


First 5 records:
    Year Industry_aggregation_NZSIOC Industry_code_NZSIOC Industry_name_NZSIOC  \
0  2024                     Level 1                99999       All industries   
1  2024                     Level 1                99999       All industries   
2  2024                     Level 1                99999       All industries   
3  2024                     Level 1                99999       All industries   
4  2024                     Level 1                99999       All industries   

                Units Variable_code  \
0  Dollars (millions)           H01   
1  Dollars (millions)           H04   
2  Dollars (millions)           H05   
3  Dollars (millions)           H07   
4  Dollars (millions)           H08   

                                     Variable_name      Variable_category  \
0                                     Total income  Financial performance   
1  Sales, government funding, grants and subsidies  Financial performance   
2                Interest, d

In [20]:
print("\nNumber of rows:", df_csv.shape[0])
print("Number of columns:", df_csv.shape[1])
print("\nMissing values per column:\n", df_csv.isnull().sum())


Number of rows: 55620
Number of columns: 10

Missing values per column:
 Year                           0
Industry_aggregation_NZSIOC    0
Industry_code_NZSIOC           0
Industry_name_NZSIOC           0
Units                          0
Variable_code                  0
Variable_name                  0
Variable_category              0
Value                          0
Industry_code_ANZSIC06         0
dtype: int64


In [21]:
stats = df_csv.describe()
print("\nStatistical Summary:\n", stats)


Statistical Summary:
                Year
count  55620.000000
mean    2018.500000
std        3.452084
min     2013.000000
25%     2015.750000
50%     2018.500000
75%     2021.250000
max     2024.000000
