In [1]:
from sklearn import datasets
iris = datasets.load_iris()

In [2]:

dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [3]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(iris.data,iris.target,train_size=0.8)


In [5]:
model.fit(X_train,y_train)

LogisticRegression()

In [6]:
model.score(X_test,y_test)

0.9

In [7]:
y_predicted = model.predict(X_test)

In [8]:
label_map = {
    0: "setosa",
    1: "versicolor",
    2: "virginica"
}

# Replace numeric predictions with names
y_predicted_named = [label_map[label] for label in y_predicted]
y_test_named =[label_map[label] for label in y_test]


In [9]:
y_predicted_named

['setosa',
 'setosa',
 'versicolor',
 'versicolor',
 'versicolor',
 'setosa',
 'virginica',
 'virginica',
 'versicolor',
 'versicolor',
 'versicolor',
 'virginica',
 'virginica',
 'versicolor',
 'setosa',
 'versicolor',
 'virginica',
 'versicolor',
 'virginica',
 'setosa',
 'versicolor',
 'virginica',
 'virginica',
 'versicolor',
 'virginica',
 'virginica',
 'virginica',
 'versicolor',
 'setosa',
 'versicolor']

In [10]:
y_test_named

['setosa',
 'setosa',
 'virginica',
 'versicolor',
 'virginica',
 'setosa',
 'virginica',
 'virginica',
 'versicolor',
 'versicolor',
 'versicolor',
 'virginica',
 'virginica',
 'versicolor',
 'setosa',
 'versicolor',
 'virginica',
 'virginica',
 'virginica',
 'setosa',
 'versicolor',
 'virginica',
 'virginica',
 'versicolor',
 'virginica',
 'virginica',
 'virginica',
 'versicolor',
 'setosa',
 'versicolor']

In [12]:
X_test #this is the characteristics of the flower 

array([[5.4, 3.9, 1.7, 0.4],
       [4.4, 3. , 1.3, 0.2],
       [6. , 3. , 4.8, 1.8],
       [5.6, 3. , 4.1, 1.3],
       [6.2, 2.8, 4.8, 1.8],
       [4.6, 3.4, 1.4, 0.3],
       [6.8, 3. , 5.5, 2.1],
       [7.3, 2.9, 6.3, 1.8],
       [6.3, 3.3, 4.7, 1.6],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.6, 3.5, 1. ],
       [6.1, 2.6, 5.6, 1.4],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.1, 3.5, 1.4, 0.2],
       [5.6, 2.9, 3.6, 1.3],
       [6.9, 3.1, 5.1, 2.3],
       [4.9, 2.5, 4.5, 1.7],
       [7.7, 2.6, 6.9, 2.3],
       [4.7, 3.2, 1.6, 0.2],
       [6.1, 3. , 4.6, 1.4],
       [6.4, 3.1, 5.5, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [5.5, 2.3, 4. , 1.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.9, 3.2, 5.7, 2.3],
       [6.1, 3. , 4.9, 1.8],
       [6. , 2.2, 4. , 1. ],
       [5. , 3.6, 1.4, 0.2],
       [5.7, 2.8, 4.5, 1.3]])

In [13]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [14]:
iris.feature_names #these are the characteristics

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [15]:
model.predict(X_test)

array([0, 0, 1, 1, 1, 0, 2, 2, 1, 1, 1, 2, 2, 1, 0, 1, 2, 1, 2, 0, 1, 2,
       2, 1, 2, 2, 2, 1, 0, 1])

In [16]:
y_test

array([0, 0, 2, 1, 2, 0, 2, 2, 1, 1, 1, 2, 2, 1, 0, 1, 2, 2, 2, 0, 1, 2,
       2, 1, 2, 2, 2, 1, 0, 1])

In [17]:
model.score(X_test,y_test)

0.9

In [24]:
import pandas as pd

# 1. Create DataFrame from X_test with feature names
df_test = pd.DataFrame(
    X_test,
    columns=iris.feature_names
)
df_train = pd.DataFrame(
    X_train,
    columns=iris.feature_names
)

# 2. Add actual and predicted labels (numeric)
df_test["actual_label"] = y_test
df_test["predicted_label"] = y_predicted

# 3. Map numeric labels to flower names
label_map = {
    0: "setosa",
    1: "versicolor",
    2: "virginica"
}

df_test["actual_name"] = df_test["actual_label"].map(label_map)
df_test["predicted_name"] = df_test["predicted_label"].map(label_map)

# 4. Optional: see only meaningful columns
df_test[[
    "sepal length (cm)",
    "sepal width (cm)",
    "petal length (cm)",
    "petal width (cm)",
    "actual_name",
    "predicted_name"
]].head()


,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),actual_name,predicted_name
0,5.4,3.9,1.7,0.4,setosa,setosa
1,4.4,3.0,1.3,0.2,setosa,setosa
2,6.0,3.0,4.8,1.8,virginica,versicolor
3,5.6,3.0,4.1,1.3,versicolor,versicolor
4,6.2,2.8,4.8,1.8,virginica,versicolor


In [25]:
df_test.loc[1]

sepal length (cm)       4.4
sepal width (cm)        3.0
petal length (cm)       1.3
petal width (cm)        0.2
actual_label              0
predicted_label           0
actual_name          setosa
predicted_name       setosa
Name: 1, dtype: object

In [26]:
df_test.iloc[1]

sepal length (cm)       4.4
sepal width (cm)        3.0
petal length (cm)       1.3
petal width (cm)        0.2
actual_label              0
predicted_label           0
actual_name          setosa
predicted_name       setosa
Name: 1, dtype: object

In [37]:
sub = df_test.loc[:, [
    "sepal length (cm)",
    "sepal width (cm)",
    "petal length (cm)"
]]

print(sub)


    sepal length (cm)  sepal width (cm)  petal length (cm)
0                 5.4               3.9                1.7
1                 4.4               3.0                1.3
2                 6.0               3.0                4.8
3                 5.6               3.0                4.1
4                 6.2               2.8                4.8
5                 4.6               3.4                1.4
6                 6.8               3.0                5.5
7                 7.3               2.9                6.3
8                 6.3               3.3                4.7
9                 5.7               3.0                4.2
10                5.7               2.6                3.5
11                6.1               2.6                5.6
12                6.8               3.2                5.9
13                6.7               3.1                4.4
14                5.1               3.5                1.4
15                5.6               2.9                3

In [41]:
# GitHub Copilot

# Build a DataFrame with all 150 iris samples, include actual and predicted labels/names
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df["actual_label"] = iris.target
df["predicted_label"] = model.predict(iris.data)
df["actual_name"] = df["actual_label"].map(label_map)
df["predicted_name"] = df["predicted_label"].map(label_map)

# Optional: ensure consistent column order
df = df[[
    "sepal length (cm)",
    "sepal width (cm)",
    "petal length (cm)",
    "petal width (cm)",
    "actual_label",
    "predicted_label",
    "actual_name",
    "predicted_name"
]]

In [42]:
print((df.isnull()).sum())

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
actual_label         0
predicted_label      0
actual_name          0
predicted_name       0
dtype: int64


In [47]:
import numpy as np
df.loc[10:15,"sepal length (cm)"] = np.nan
df.loc[20:25,"sepal length (cm)"] = np.nan


In [48]:
df['sepal length (cm)'].fillna

<bound method NDFrame.fillna of 0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal length (cm), Length: 150, dtype: float64>

In [49]:
df['petal width (cm)'].fillna

<bound method NDFrame.fillna of 0      0.2
1      0.2
2      0.2
3      0.2
4      0.2
      ... 
145    2.3
146    1.9
147    2.0
148    2.3
149    1.8
Name: petal width (cm), Length: 150, dtype: float64>